name: Server workflow

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ACCESS_SECRET: 'ACCESS_SECRET'
  REFRESH_SECRET: 'REFRESH_SECRET'
  SERVER_SECRET: 'SERVER_SECRET'

permissions:
  contents: write
  actions: read
  checks: write
  packages: write

jobs:
  filter-dockerfile:
    name: Check Dockerfile
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.dockerfile }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            dockerfile:
              - '.devcontainer/Dockerfile'

  build-push:
    name: Build and push Docker image
    needs: filter-dockerfile
    if: ${{ needs.filter-dockerfile.outputs.dockerfile_changed == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=nightly,enable=${{ github.ref != format('refs/heads/{0}', 'master') }}
            type=ref,event=pr

      - name: Set up Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: mode=max
          context: .devcontainer

  FormatAndLint:
    name: 'Format & Lint'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      project: ${{ steps.filter.outputs.project }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - id: 'getBranch'
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
              echo "test=$(git rev-parse HEAD~1)" >> "$GITHUB_OUTPUT"
          else
              echo "test='HEAD'" >> "$GITHUB_OUTPUT"
          fi

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 23.7
          cache: 'pnpm'

      - run: pnpm -r i && npm run format && npm run lint

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          skip_dirty_check: false

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        id: filter
        with:
          base: ${{ steps.getBranch.outputs.test }}
          filters: |
            project:
              - '**/*.json'
              - '**/*.ts'
              - 'pnpm-lock.yaml'

  Test:
    needs:
      - FormatAndLint
      - build-push
    if: ${{ needs.FormatAndLint.outputs.project == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
      contents: write
      pull-requests: write
    name: Test ${{ matrix.object }}
    strategy:
      matrix:
        object: [service, requesters, etc]
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6
        with:
          push: always
          runCmd: |
            cd server
            npm run test:${{ matrix.object }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: reports_${{ matrix.object }}
          path: |
            ./server/reports/${{ matrix.object }}.xml
            ./server/coverage/${{ matrix.object }}.txt

  WrapUp:
    name: 'Wrap up'
    needs:
      - Test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')

      - name: Delete GitHub Actions Comments
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ github.token }}
          delete_user_name: 'github-actions[bot]'
          issue_number: ${{ github.event.number }}

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        if: contains(needs.Test.result, 'success') 
        with:
          pattern: reports_*

      - name: Requesters
        if: contains(needs.Test.result, 'success') 
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: Requesters test result
          coverage-path: ./reports_requesters/coverage/requesters.txt
          create-new-comment: true

      - name: Service
        if: contains(needs.Test.result, 'success') 
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: Service test result
          coverage-path: ./reports_service/coverage/service.txt
          create-new-comment: true

      - uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
        if: contains(needs.Test.result, 'success') 
        with:
          artifact: /reports_(.*)/
          name: Tests runtime
          path: '**/*.xml'
          reporter: jest-junit
